require: 'rubocop-rspec'
AllCops:
  Exclude:
    - 'bin/*'
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'db/migrate/20160430112623_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb'
    - 'db/migrate/20160430112627_change_collation_for_tag_names.acts_as_taggable_on_engine.rb'
    - 'db/migrate/20160430112624_add_missing_unique_indices.acts_as_taggable_on_engine.rb'
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'
Rails:
  Enabled: true
Documentation:
  Enabled: false